In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [65]:
x=pd.read_csv(r"C:\Users\snaha\Downloads\LR_X.csv")
y=pd.read_csv(r"C:\Users\snaha\Downloads\LR_Y.csv")
print(x)
print(y)

       X1    X2    X3
0    0.26  0.08  0.28
1    0.26  0.52  0.01
2    0.85  0.60  0.14
3    0.94  0.22  0.48
4    0.53  0.05  0.76
..    ...   ...   ...
995  0.78  0.41  0.60
996  0.76  0.71  0.86
997  0.88  0.06  0.33
998  0.28  0.40  0.41
999  0.94  0.48  0.45

[1000 rows x 3 columns]
         Y
0    1.472
1    1.802
2    1.548
3    1.390
4    2.141
..     ...
995  2.245
996  3.471
997  0.796
998  2.406
999  1.870

[1000 rows x 1 columns]

In [67]:
x.shape

(1000, 3)

In [69]:
y.shape

(1000, 1)

In [71]:
x.describe()

                X1           X2           X3
count  1000.000000  1000.000000  1000.000000
mean      0.493360     0.501480     0.493320
std       0.287477     0.287708     0.285183
min       0.000000     0.000000     0.000000
25%       0.250000     0.270000     0.250000
50%       0.480000     0.495000     0.490000
75%       0.740000     0.750000     0.730000
max       1.000000     1.000000     1.000000

# Append a column with the independent variable X

In [74]:
ones=np.ones((1000,1))
ones.shape

(1000, 1)

In [76]:
ones[:10]

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [78]:
new_x=np.concatenate((ones,x),axis=1)
new_x

array([[1.  , 0.26, 0.08, 0.28],
       [1.  , 0.26, 0.52, 0.01],
       [1.  , 0.85, 0.6 , 0.14],
       ...,
       [1.  , 0.88, 0.06, 0.33],
       [1.  , 0.28, 0.4 , 0.41],
       [1.  , 0.94, 0.48, 0.45]])

In [80]:
res1=np.linalg.inv(np.dot(np.transpose(new_x),new_x))
#print(res1)
res1.shape

(4, 4)

In [82]:
res2=np.dot(np.transpose(new_x),y)
res2.shape

(4, 1)

In [84]:
res=np.dot(res1,res2)
print(res)

[[ 1. ]
 [-1.2]
 [ 2.1]
 [ 2.2]]

# The equation of the linear regression is Y=1.0-1.2x1+2.1x2+2.2*x3

In [87]:
x

       X1    X2    X3
0    0.26  0.08  0.28
1    0.26  0.52  0.01
2    0.85  0.60  0.14
3    0.94  0.22  0.48
4    0.53  0.05  0.76
..    ...   ...   ...
995  0.78  0.41  0.60
996  0.76  0.71  0.86
997  0.88  0.06  0.33
998  0.28  0.40  0.41
999  0.94  0.48  0.45

[1000 rows x 3 columns]

# Gradient Descent

In [104]:
data=pd.read_csv(r"C:\Users\snaha\Downloads\P176.txt")

In [106]:
data.head()

      X Y
0  294 30
1  247 32
2  267 37
3  358 44
4  423 47